<?php

/**
 * PjangoPageLayoutCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PjangoPageLayoutCategory extends BasePjangoPageLayoutCategory
{
	public static function findAllAsChoice() {
		$choices = array();
		$tree = false;
	
		$treeObject = Doctrine::getTable(PjangoPageLayoutCategory)->getTree();
		$rootColumnName = $treeObject->getAttribute('rootColumnName');
	
		foreach ($treeObject->fetchRoots() as $root) {
			$options = array('root_id' => $root->$rootColumnName);
			$tree = $treeObject->fetchTree($options);
		}
	
		if (!$tree) return $choices;
	
		foreach ($tree as $node) {
			$choices[$node['id']] =  str_repeat('--', $node['level']).$node->name;
		}
			
		return $choices;
	}	

}