PhoneType:   
    tableName: pjango_phonetype
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        name: string(35)             


Phone:   
    tableName: pjango_phone
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        country_code: string(3)
        area_code: string(6)
        phone_number: string(15)
        extention: string(5)
        is_default: boolean        
        phone_type_id: integer

    relations:
        PhoneType:
            foreignType: one           
                  

EmailType:   
    tableName: pjango_emailtype
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        name: string(35)             


Email:   
    tableName: pjango_email
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        email: string(100)
        is_default: boolean
        email_type_id: integer
 
    relations:
        EmailType:
            foreignType: one
            
AddressType:   
    tableName: pjango_addresstype
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        name: string(35)             


Address:   
    tableName: pjango_address
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true

        country: string(100)
        city: string(100)        
        district: string(100)
        street: string(100)
        address: string(100)  
        zip: string(10)
        
        country_id: integer     
        city_id: integer
        district_id: integer
        address_type_id: integer
 
    relations:
        AddressType:
            foreignType: one
            
PjangoPageLayoutCategory:
    tableName: pjango_pagelayout_category
    actAs:
        NestedSet:
            hasManyRoots: true
            rootColumnName: root_id

    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
                   
        name: string(100)        
        
        
PjangoPageLayout:  
    tableName: pjango_pagelayout
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true 
                
        object_id: integer
        category_id: integer
        content_type_id: integer        
        
    relations:
        ContentType:
            local: content_type_id
            foreign: id    
        Category:
            class: PjangoPageLayoutCategory
            local: category_id
            foreign: id                    
            
PjangoLocation:   
    tableName: pjango_location
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        code: string(35)            
        name: string(100)
        plate: string(4)
        region: string(35)
        population: integer(10)
        latitude: float
        longitude: float
        weight: integer
        
        parent_id: integer
    relations:
        Parent:
            class: PjangoLocation
            local: parent_id
            foreign: id